spring:
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://ec2-34-254-120-2.eu-west-1.compute.amazonaws.com:5432/d8dek7llts1ldi #jdbc:postgresql://192.168.0.134:5432/postgres_check  backup DB
    username: rduonhwzleytpd
    password: 986c2a4939363226f411b837599ce5a3b89a65006f63b3697a48e93b04ec2ff9
    continueOnError: true
    initialize: false
    initialSize: 0
    timeBetweenEvictionRunsMillis: 5000
    minEvictableIdleTimeMillis: 5000
    minIdle: 0

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
      naming_strategy: org.hibernate.cfg.DefaultNamingStrategy
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop
        temp:
          use_jdbc_metadata_defaults: false